// <auto-generated />
using System;
using Infotecs_WebApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infotecs_WebApi.Infrastructure.Migrations
{
    [DbContext(typeof(InfotecsDbContext))]
    [Migration("20250726100531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infotecs_WebApi.Domain.Entities.Result", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<double>("AverageExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageValueDefinition")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxValueDefinition")
                        .HasColumnType("double precision");

                    b.Property<double>("MedianValueDefinition")
                        .HasColumnType("double precision");

                    b.Property<double>("MinValueDefinition")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("MinimalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TimeDeltaSeconds")
                        .HasColumnType("double precision");

                    b.HasKey("FileName");

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("Infotecs_WebApi.Domain.Entities.Value", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionTime")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<double>("ValueDefinition")
                        .HasColumnType("double precision")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Values", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
